#!/bin/bash
#/ Usage: scripts/sync-vs [-u|--unity-path <path>]
#/ Synchronizes Visual Studio/Rider solution and project files with the Unity project.
#/
#/ Options:
#/   -u, --unity-path <path>    Path to the Unity installation to use. Defaults to an autodetected path based on the version of RGUnityBots.
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
repo_root="$(dirname "$source_dir")"
source "$repo_root/script/_utils.sh"

set -euo pipefail

# Parse arguments
unity_path=
while [[ $# -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in
        -u|--unity-path)
            unity_path="$1"
            shift
            ;;
        --help)
            grep '^#/' "$0" | cut -c4-
            exit 0
            ;;
        -*)
            echo "Unknown option: $key"
            exit 1
            ;;
        *)
            echo "Unknown argument: $key"
            exit 1
            ;;
    esac
done

if [ -z "$unity_path" ]; then
    unity_path=$(get_unity_path "$(get_unity_version "$repo_root/src/RGUnityBots")")
fi

echo "Using Unity at $unity_path"
echo "Syncing Visual Studio/Rider solution and project files..."
unity "$unity_path" -projectPath "$repo_root/src/RGUnityBots" -executeMethod "UnityEditor.SyncVS.SyncSolution"